### ISSUE TITLE
ways to retrieve data model of a wfs

### ISSUE THREAD

**Issue by pvgenuchten** [geo4web-testbed/topic4-general#10]
what options are available to retrieve the data model for 'bag' and 'aan'

For endpoint bag:
- http://geodata.nationaalgeoregister.nl/inspireadressen/wfs?service=WFS&request=GetCapabilities (that returns the outputformats and featuretypes)
- http://geodata.nationaalgeoregister.nl/inspireadressen/wfs?request=DescribeFeatureType&FeatureType=inspireadressen:inspireadressen
- http://geodata.nationaalgeoregister.nl/inspireadressen/wfs?TYPENAME=inspireadressen:inspireadressen&STARTINDEX=1&COUNT=1&REQUEST=getFeature (returns 1 record)

For endpoint  aan:
- http://geodata.nationaalgeoregister.nl/aan/wfs?request=GetCapabilities (that returns the outputformats and featuretypes)
- http://geodata.nationaalgeoregister.nl/aan/wfs?request=DescribeFeatureType&FeatureType=aan:aan (retrieve the data model)
- http://geodata.nationaalgeoregister.nl/aan/wfs?request=getfeature&TypeName=aan:aan&count=1 (returns 1 record)
- note that you can also have it return as json: http://geodata.nationaalgeoregister.nl/inspireadressen/wfs?TYPENAME=inspireadressen:inspireadressen&STARTINDEX=1&COUNT=1&REQUEST=getFeature&outputFormat=json

If one of these would have been an INSPIRE download service like http://services.inspire-provincies.nl/ProtectedSites/services/download_PS, then the decribeFeaturetype will return a link to the xsd that is used as a model.
- http://services.inspire-provincies.nl/ProtectedSites/services/download_PS?service=wfs&version=2.0.0&request=getcapabilities
- http://services.inspire-provincies.nl/ProtectedSites/services/download_PS?service=wfs&version=2.0.0&request=DescribeFeatureType&FeatureType=ps:ProtectedSite
- http://services.inspire-provincies.nl/ProtectedSites/resources/appschemas/ProtectedSites.xsd (throws 404 unfortunately)

**Comment by ghost** [comment]
Thanks Paul, when I execute these services then  I get for both a very simple model:
For AAN a gml:MultiSurfacePropertyType with 4attrubutes, and for inspireadressen a gml:PointPropertyType with 6 attributes, like huisnummer, huisletter, woonplaats etc. Is this all of the datamodel for this service?

**Comment by cportele** [comment]
Yes, the content model of these services is really simple.

**Comment by pvgenuchten** [comment]
check my comment in issue #8, i think the proposal should have referenced the real inspire adresses service
