### ISSUE TITLE
Design issues for the schema mapping 

### ISSUE THREAD

**Issue by ghost** [geo4web-testbed/topic4-general#11]
It will be very unlikely that our source will  fit 100% to the schema.org vocabulary. Therefore we will need to make decisions on how we will make the mapping if a 100% fit is not possible.

_Issues_
1.The XSDs contain model restrictions (for cardinality etc) and sequences. I suggest to ignore this and not model restrictions/sequences.

2.Not everything that needs to be modeled is present in schema.org. I propose that we make suggestions for an extension in schema.org or, when the element-to-be-mapped is not important, to ignore the element. Example: we need a property for "source" in the AAN. There is a property schema:source, but this is via domain/range bound to the classes schema:Artery and chema:AnatomicalStructure. It would be tempting to use dcterms:source instead but this property does not belong to the schema.org vocabulary. How search engines use external vocs next to schema.org must be researched.

3.Schema.org does not have a property for the SRS. It assumes WGS84.

4.Are we creating JSON-LD from the WFS on a record level (i.e. we will create one HTML page per WMS record) or per set of features? This influences if we use "@graph" or not in the JSON-LD. Graph refers to collections. It is possible though to use "@graph" even if you have only one resource in the graph, so we can be flexible. But if we are certain that we proxy everithing on the record level then we can omit "@graph" in the JSON-LD

**Comment by ghost** [comment]
For issue 2: we could add other vocabularies in the JSON-LD. This is useful for the LD users. It just wont be read by the search engine, this we have to realise.

**Comment by cportele** [comment]
@liekeverhelst 
Re item 2 we said: "For all resources and properties that do not map to schema.org, we will analyse and decide in the design phase how we extend schema.org (https://schema.org/docs/extension.html; for the testbed, we will use external extensions)." So, I assume we will create a 1-to-1 extension for every piece of information that does not map to schema.org.

Re item 1: I agree.

Re item 3: Yes, we will use WGS 84 geographic.

**Comment by ghost** [comment]
@cportele ok lets see how far we get with creating extensions, if this remains practical. I will make a list of all things that must be in that extension

**Comment by ghost** [comment]
@cportele @pvgenuchten I started an extension to schema.org https://github.com/geo4web-testbed/geo-extension-to-schemaorg . For the moment it is just a container to collect all the missing things. Later we can normalise this to something useful.

**Comment by ghost** [comment]
Moved to https://github.com/geo4web-testbed/geo-extension-to-schemaorg
