### ISSUE TITLE
Potential administrative dataset

### ISSUE THREAD

**Issue by pvgenuchten** [geo4web-testbed/topic4-general#12]
Discussed with rivm today the topic4 contents, They mentioned that if we are looking for a data-linking usecase, They would be happy to contribute knowledge and data, for example the voedselconsumptiepeiling, which will soon be released as open data. http://www.rivm.nl/Onderwerpen/V/Voedselconsumptiepeiling we can probably link that data on 4digit postalcode level.

**Comment by cportele** [comment]
As far as I understand the content, this looks good to me.

**Comment by ghost** [comment]
@pvgenuchten indeed looks nice & original ;-) ,  what exactly is represented in the address/location? I could not find it except "the place where the food was consumed"..

**Comment by ghost** [comment]
We have decided to use this dataset: https://geozet.koop.overheid.nl/overuwbuurt/overheidnl/
Todo: make it avail as LD, meaning: dereferenceable and queryable

**Comment by cportele** [comment]
@liekeverhelst @pvgenuchten @azahnen @lvdbrink In case anyone wants to "see" that Bekendmakingen data on a map: I have added the live WFS for this dataset to our data map on ArcGIS Online: http://arcg.is/1O6s7aR. Note that I have excluded the summary layers (only the Bekendmakingen punt/vlak and the Gemeentegrenzen layers are included).

I have deselected the Bekendmakingen polygons as there are quite a few with intersections, but you can switch it on again (under Details > Content). 

Note that if you zoom out from the initial zoom level, the addresses will no longer be shown.
