### ISSUE TITLE
Check if xslt or sesame or hydra is a good technology to create jsonld from iso19139

### ISSUE THREAD

**Issue by Delawen** [geo4web-testbed/topic4-general#3]
At first we consider using xsl transformations to generate JSONLD, but after some bad experiences we decided to drop that idea. For simple usecases, generating json from xslt may work, but when complex characters, json strings and/or quotes (single or multiple) are involved, xslt may generate invalid content unless we create a very complex structure of loop templates which replicates what other json libraries already do.

So now we are looking for some library that can be helpful here. Sesame is already included in GeoNetwork. Hydra is another library recommended for JSONld.

**Comment by Delawen** [comment]
**XSLT** means a lot of work: we have to replicate what a complex json library conversor does in XSLT. 
**Sesame** already incorporated in GeoNetwork, but on an old version (1.2.7). This means two things: no documentation and no native support for JSONld.
**Upgraded Sesame** we can upgrade the library dependency for GeoNetwork, but that would mean a lot of work migrating the current thesaurus code.

Options we are considering now: dropping jsonld in favor of RDFa or using hydra-java.

**Comment by Delawen** [comment]
https://developers.google.com/structured-data/testing-tool/

**Comment by Delawen** [comment]
Suggested solution:
- Each schema will have a configuration file which defines the xpath of the properties to display on JOSN-ld
- There will be a set of generic java annotated classes that will work as information bean for JSON-ld
- GeoNetwork will have a Spring MVC endpoint that converts this java classes to JSON (JSON-ld).

So, when a new schema is added, a new configuration file will be needed to define where are the properties on that schema.

**Comment by pvgenuchten** [comment]
As a note, [sesame](http://rdf4j.org/sesame/2.7/apidocs/org/openrdf/rio/RDFFormat.html) sure is the best option here, but the limited resources in this project (this issue is not the core project goal), made us decide to go for a quick fix using json-serialisation of a java bean

Another quick fix is that, in stead of adding schema.org/Dataset as a new schema-profile, we will add schema.org as a json-ld outputformat of iso19139.
